// Generated by CoffeeScript 1.10.0
(function() {
  var Account, db, mongoose, should;

  should = require('should');

  mongoose = require('mongoose');

  Account = require('../models/account.js');
  Session = require('../models/session.js');
  Binary = require('../models/binary_file.js');

  describe('Session', function(){
    before(function(done){
      db = mongoose.connect('mongodb://localhost/test');
      
      done();
    });
    after(function(done){
      //db = mongoose.connect('mongodb://localhost/test');
      done();
    });
    beforeEach(function(done){
      session = new Session({
        secret: "v9CnUgnfapm_zLJG3Eja3Wf6li2bfPCd",
        user_id: 1
      });
      session.save(function(error){
        if(error)
          console.log('error' + error.message)
        done();
      });
    });
    it('finds a session by user_id', function(done) {
      Session.findOne({
        user_id: 1
      }, function(err, session) {
        session.secret.should.eql('v9CnUgnfapm_zLJG3Eja3Wf6li2bfPCd');
        console.log('   session: ', session.secret);
        done();
      });
    });
    afterEach(function(done) {
      Session.remove({}, function() {
        done();
      });
    });
  });

  describe('Account', function() {
    before(function(done) {
      //db = mongoose.connect('mongodb://localhost/test');
      done();
    });
    after(function(done) {
      mongoose.connection.close();
      done();
    });
    beforeEach(function(done) {
      var account;
      account = new Account({
        username: '12345',
        password: 'testy'
      });
      account.save(function(error) {
        if (error) {
          console.log('error' + error.message);
        } else {
          console.log('no error');
        }
        done();
      });
    });
    it('find a user by username', function(done) {
      Account.findOne({
        username: '12345'
      }, function(err, account) {
        account.username.should.eql('12345');
        account.id.should.above(0);
        console.log('   username: ', account.username);
        done();
      });
    });
    afterEach(function(done) {
      Account.remove({}, function() {
        done();
      });
    });
  });

}).call(this);
