// Generated by CoffeeScript 1.10.0
(function() {
  var Account, BinaryFile, LocalStrategy, app, bodyParser, cookieParser, express, favicon, flash, logger, mongoose, passport, path, routes, users;

  express = require('express');

  path = require('path');

  favicon = require('serve-favicon');

  logger = require('morgan');

  cookieParser = require('cookie-parser');

  bodyParser = require('body-parser');

  mongoose = require('mongoose');

  passport = require('passport');

  LocalStrategy = require('passport-local').Strategy;

  flash = require('connect-flash');

  routes = require('./routes/index');

  users = require('./routes/users');

  var responseTime = require('response-time');
  var axios = require('axios');
  

  app = express();

  app.set('views', path.join(__dirname, 'views'));

  app.set('view engine', 'jade');

  app.use(responseTime());

  app.use(favicon(__dirname + '/public/favicon.ico'));

  app.use(logger('dev'));

  app.use(bodyParser.json());

  app.use(bodyParser.urlencoded({
    extended: false
  }));

  app.use(cookieParser());

  app.use(require('express-session')({
    secret: 'keyboard cat',
    resave: false,
    saveUninitialized: false
  }));

  app.use(passport.initialize());

  app.use(flash());

  app.use(passport.session());

  app.use(express["static"](path.join(__dirname, 'public')));

  app.use('/', routes);

  Account = require('./models/account');

  BinaryFile = require('./models/binary_file');

  passport.use(new LocalStrategy(Account.authenticate()));

  passport.serializeUser(Account.serializeUser());

  passport.deserializeUser(Account.deserializeUser());

  mongoose.Promise = global.Promise;

  mongoose.connect('mongodb://localhost/passport_local_mongoose_express4');

  app.use(function(req, res, next) {
    var err;
    err = new Error('Not Found');
    err.status = 404;
    return next(err);
  });

  if (app.get('env') === 'development') {
    app.use(function(err, req, res, next) {
      res.status(err.status || 500);
      return res.render('error', {
        message: err.message,
        error: err
      });
    });
  }

  app.use(function(err, req, res, next) {
    res.status(err.status || 500);
    return res.render('error', {
      message: err.message,
      error: {}
    });
  });

  module.exports = app;

}).call(this);
