// Generated by CoffeeScript 1.10.0
(function() {
  var express, router;

  express = require('express');

  router = express.Router();


  /* GET users listing. */

  router.get('/', function(req, res, next) {
    return res.send('respond with a resource');
  });

  module.exports = router;

}).call(this);
