// Generated by CoffeeScript 1.10.0
(function() {
  var BinaryFile, Schema, mongoose, passportLocalMongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  passportLocalMongoose = require('passport-local-mongoose');

  BinaryFile = new Schema({
    binary: Buffer
  });

  // BinaryFile.plugin(passportLocalMongoose);

  module.exports = mongoose.model('BinaryFile', BinaryFile);

}).call(this);
